language: go
go:
  - 1.10.x
  - 1.11.x

matrix:
  fast_finish: true

services:
  - docker

before_install:
  - docker pull redislabs/rejson
  - docker run -d -p 6379:6379 --name redis-rejson redislabs/rejson:latest
  - docker ps -a
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5

install:
  - dep ensure

script:
  - go test -v .
  - go test -covermode=count -coverprofile=profile.cov .
  - golangci-lint run ./...

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci

